typography_spectrum: 0.5037376945838332
color:
  brandStrength: 0.38884035288356245
  lightness: 0.918774702353403
  saturation: 0.3895674841478467
  rhythmicContrast: 0.9634040717501193
  brandColors:
    - '#000000'
    - '#6A5C4E'
    - '#BDAC9B'
    - '#948271'
    - '#E2D8CA'
layout_spectrum: 0.9470565568190068
analytics:
  google: UA-67989701-1
author:
  name: Michel Wernars
  email: info@fitbalance.nl
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bbcbb628-ddac-442d-86fc-a740b2504e37.png
name: FitBalance
navigation:
  - name: Tarieven
    id: 692dc592-c995-4715-b30f-81ce70a8403b
    type: content
  - name: Contact
    id: df5a0552-9b69-4adc-a7e0-65dc22f9489b
    type: content
title: FitBalance
description: Uitgaan van je eigen kracht
